use utoipa::OpenApi;

use crate::controller::{
    blocks, borrow_apr, borrowed, buyback, buyback_total, current_lenders, daily_positions,
    deposit_suspension, distributed, earn_apr, earnings, get_position_debt_value,
    historical_lenders, historically_liquidated, historically_opened, historically_repaid,
    history_stats, incentives_pool, interest_repayments, lease_value_stats, leased_assets,
    leases, leases_monthly, leases_search, liquidations, loans_by_token, loans_granted,
    lp_withdraw, ls_loan_closing, ls_opening, ls_openings, monthly_active_wallets, open_interest,
    open_position_value, open_positions_by_token, optimal, pnl_over_time, position_buckets,
    positions, prices, realized_pnl, realized_pnl_data, realized_pnl_stats, realized_pnl_wallet,
    revenue, revenue_series, subscribe, supplied_borrowed_series, supplied_funds,
    total_tx_value, total_value_locked, txs, unrealized_pnl, unrealized_pnl_by_address,
    utilization_level, utilization_levels, version,
};

#[derive(OpenApi)]
#[openapi(
    info(
        title = "Nolus ETL API",
        version = "3.14.23",
        description = "REST API for the Nolus blockchain ETL service. Provides analytics, position data, lending metrics, and market data.",
        license(name = "MIT")
    ),
    tags(
        (name = "Protocol Analytics", description = "Protocol-wide metrics and statistics"),
        (name = "Position Analytics", description = "Position and lease analytics"),
        (name = "Lending Analytics", description = "Lending and liquidation data"),
        (name = "Market Data", description = "Price and market information"),
        (name = "Wallet Analytics", description = "Wallet-specific data and transactions"),
        (name = "Record Lookup", description = "Individual record lookups"),
        (name = "Push Notifications", description = "Push notification subscription management")
    ),
    paths(
        // Protocol Analytics
        total_value_locked::index,
        total_tx_value::index,
        revenue::index,
        borrowed::index,
        supplied_funds::index,
        blocks::index,
        version::index,
        supplied_borrowed_series::index,
        monthly_active_wallets::index,
        revenue_series::index,
        borrow_apr::index,
        earn_apr::index,
        utilization_level::index,
        utilization_levels::index,
        optimal::index,
        deposit_suspension::index,
        buyback::index,
        buyback_total::index,
        distributed::index,
        incentives_pool::index,
        // Position Analytics
        open_position_value::index,
        open_interest::index,
        unrealized_pnl::index,
        realized_pnl_stats::index,
        leased_assets::index,
        loans_by_token::index,
        open_positions_by_token::index,
        position_buckets::index,
        positions::index,
        positions::export,
        leases_monthly::index,
        daily_positions::index,
        // Lending Analytics
        current_lenders::index,
        liquidations::index,
        liquidations::export,
        lease_value_stats::index,
        historical_lenders::index,
        historical_lenders::export,
        loans_granted::index,
        historically_liquidated::index,
        historically_liquidated::export,
        historically_repaid::index,
        historically_repaid::export,
        interest_repayments::index,
        interest_repayments::export,
        historically_opened::index,
        historically_opened::export,
        realized_pnl_wallet::index,
        realized_pnl_wallet::export,
        // Market Data
        prices::index,
        // Wallet Analytics
        unrealized_pnl_by_address::index,
        pnl_over_time::index,
        txs::index,
        leases::index,
        ls_loan_closing::index,
        realized_pnl::index,
        get_position_debt_value::index,
        realized_pnl_data::index,
        history_stats::index,
        leases_search::index,
        earnings::index,
        // Record Lookup
        ls_opening::index,
        ls_openings::index,
        lp_withdraw::index,
        // Push Notifications
        subscribe::get_index,
        subscribe::post_index,
    ),
    components(
        schemas(
            // Protocol Analytics responses
            total_value_locked::Response,
            total_tx_value::Response,
            revenue::Response,
            borrowed::Response,
            supplied_funds::Response,
            blocks::Response,
            version::Response,
            supplied_borrowed_series::SuppliedBorrowedPoint,
            monthly_active_wallets::MonthlyActiveWalletResponse,
            revenue_series::RevenueSeriesPointResponse,
            borrow_apr::BorrowAprPoint,
            earn_apr::Response,
            utilization_level::UtilizationPoint,
            utilization_levels::UtilizationLevelsResponse,
            utilization_levels::ProtocolUtilization,
            optimal::Response,
            deposit_suspension::Response,
            buyback::BuybackPoint,
            buyback_total::Response,
            distributed::Response,
            incentives_pool::Response,
            // Position Analytics responses
            open_position_value::Response,
            open_interest::Response,
            unrealized_pnl::Response,
            realized_pnl_stats::Response,
            leased_assets::LeasedAssetResponse,
            loans_by_token::TokenLoanResponse,
            open_positions_by_token::TokenPositionResponse,
            position_buckets::PositionBucketResponse,
            positions::PositionResponse,
            leases_monthly::LeasesMonthlyResponse,
            daily_positions::DailyPositionsPointResponse,
            // Lending Analytics responses
            current_lenders::CurrentLenderResponse,
            liquidations::Liquidation,
            lease_value_stats::LeaseValueStatResponse,
            historical_lenders::HistoricalLenderResponse,
            loans_granted::LoanGrantedResponse,
            historically_liquidated::HistoricallyLiquidatedResponse,
            historically_repaid::HistoricallyRepaidResponse,
            interest_repayments::InterestRepayment,
            historically_opened::HistoricallyOpenedResponse,
            realized_pnl_wallet::RealizedPnlWalletResponse,
            // Market Data responses
            prices::PricePoint,
            // Wallet Analytics responses
            unrealized_pnl_by_address::Response,
            pnl_over_time::PnlOverTimeResponse,
            txs::TxResponse,
            leases::LeaseResponse,
            ls_loan_closing::LsLoanClosingResponse,
            realized_pnl::Response,
            get_position_debt_value::Response,
            get_position_debt_value::AmountResponse,
            realized_pnl_data::RealizedPnlDataResponse,
            history_stats::Response,
            leases_search::LeaseSearchResponse,
            earnings::Response,
            // Record Lookup responses
            ls_opening::LsOpeningResponse,
            ls_openings::LsOpeningsResponse,
            lp_withdraw::LpWithdrawResponse,
            // Push Notifications
            subscribe::SubscribeCheckResponse,
            subscribe::SubscribeRequest,
            subscribe::SubscriptionData,
            subscribe::SubscriptionKeys,
        )
    )
)]
pub struct ApiDoc;
